telegram:
  bot:
    token: 1173704512:AAHR_x7ZMGREvTYV0U0QpHv3JgvueL86eVg

yandex:
  translate:
    apiKey: trnsl.1.1.20200426T075855Z.cd9c3e862ff987a1.451219ac132840888d356bb87d70eafb75381bbc

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telegram_bot?useSSL=false&characterEncoding=UTF-8
    sqlScriptEncoding: UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update